if (self.CavalryLogger) { CavalryLogger.start_js(["ls0uTR6"]); }

__d("CometGamingCoplayRejoinRoomModalContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="3964182193665550"}),null);
__d("CometGamingCoplayRejoinRoomModalContainerQuery$Parameters",["CometGamingCoplayRejoinRoomModalContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGamingCoplayRejoinRoomModalContainerQuery_facebookRelayOperation"),metadata:{},name:"CometGamingCoplayRejoinRoomModalContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingForYouRootHeroBannerQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4201624886616555",metadata:{},name:"CometGamingForYouRootHeroBannerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingForYouRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5078560462159527"}),null);
__d("CometGamingForYouRootQuery$Parameters",["CometGamingForYouRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGamingForYouRootQuery_facebookRelayOperation"),metadata:{},name:"CometGamingForYouRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingLeftRailContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4461614057262129"}),null);
__d("CometGamingLeftRailContainerQuery$Parameters",["CometGamingLeftRailContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGamingLeftRailContainerQuery_facebookRelayOperation"),metadata:{},name:"CometGamingLeftRailContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingVideoGameHubHeaderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3866730166752555",metadata:{},name:"CometGamingVideoGameHubHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingVideoGameHubRootContentQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4760052907338860",metadata:{},name:"CometGamingVideoGameHubRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("buildCometGamingRoute.entrypoint",["CometGamingCoplayRejoinRoomModalContainerQuery$Parameters","CometGamingLeftRailContainerQuery$Parameters","JSResourceForInteraction","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";a=c("createContentAreaCompoundEntryPointBuilder")(c("JSResourceForInteraction")("CometGamingRoot.react").__setRef("buildCometGamingRoute.entrypoint"),function(a){return{coplayRejoinRoomModalQueryReference:{parameters:b("CometGamingCoplayRejoinRoomModalContainerQuery$Parameters"),variables:{}},leftRailQueryReference:{parameters:b("CometGamingLeftRailContainerQuery$Parameters"),variables:{}}}});g["default"]=a}),98);
__d("CometGamingForYouRoot.entrypoint",["CometGamingForYouRootHeroBannerQuery$Parameters","CometGamingForYouRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGamingRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometGamingRoute.entrypoint")(c("JSResourceForInteraction")("CometGamingForYouRoot.react").__setRef("CometGamingForYouRoot.entrypoint"),function(a){a=d("WebPixelRatio").get();a={UFI2CommentsProvider_commentsKey:"CometGamingForYouRootQuery",entrypoint:"COMET",feedLocation:"GAMING_FEED",feedbackSource:1,privacySelectorRenderLocation:"COMET_GAMING_FEED",renderLocation:"gaming_feed",scale:a};return{extraProps:{variables:a},queries:{cometGamingForYouRootQueryReference:{parameters:b("CometGamingForYouRootQuery$Parameters"),variables:babelHelpers["extends"]({},a)},heroBannerQueryReference:{parameters:b("CometGamingForYouRootHeroBannerQuery$Parameters"),variables:{}}}}});g["default"]=a}),98);
__d("CometGamingVideoGameHubRoot.entrypoint",["CometGamingVideoGameHubHeaderQuery$Parameters","CometGamingVideoGameHubRootContentQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGamingRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";var h=d("WebPixelRatio").get();a=c("buildCometGamingRoute.entrypoint")(c("JSResourceForInteraction")("CometGamingVideoGameHubRoot.react").__setRef("CometGamingVideoGameHubRoot.entrypoint"),function(a){return{queries:{contentQueryReference:{parameters:b("CometGamingVideoGameHubRootContentQuery$Parameters"),variables:{game_id:a.routeProps.game_id,scale:h}},headerQueryReference:{parameters:b("CometGamingVideoGameHubHeaderQuery$Parameters"),variables:{params:{game_id:a.routeProps.game_id}}}}}});g["default"]=a}),98);
__d("CometGamingVideoRootContentQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4343315232413375"}),null);